"""
RepoProfile — 仓库级别的配置抽象。

每个支持的仓库（django, pytest, sympy, sklearn 等）实现一个 RepoProfile 子类，
封装该仓库特有的：源码→测试映射、测试命令构建、崩溃指示器、测试代码生成模板等。

Pipeline 各阶段通过 RepoProfile 接口访问仓库特定逻辑，不再硬编码 `if is_django:` 分支。
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from src.modules.validation.profiles.base import BaseProfile


@dataclass
class RepoProfile:
    """仓库 Profile 基类。子类覆盖属性和方法以适配特定仓库。"""

    # ── 身份 ──
    repo: str = ""                          # "django/django"
    test_framework: str = "pytest"          # "pytest" | "unittest"

    # ── 源码→测试映射 ──
    source_to_test_mapping: dict[str, list[str]] = field(default_factory=dict)
    test_root: str = "tests"               # 测试目录根

    # ── 测试命令 ──
    test_cmd_template: str = "pytest {targets} -v --tb=short"

    # ── 过滤 ──
    disallowed_test_prefixes: list[str] = field(default_factory=list)

    # ── 崩溃指示器（仓库特有，会与通用指示器合并）──
    extra_crash_indicators: list[tuple[str, str]] = field(default_factory=list)

    # ── 合成测试模板 ──
    test_base_class: str = ""               # "TestCase" for Django, "" for pytest
    test_imports: list[str] = field(default_factory=list)

    # ── 方法 ──

    def infer_test_modules(self, source_file: str, repo_root: Path | None = None) -> list[str]:
        """根据源文件路径推断相关的测试模块/文件。

        默认策略：
        1. 先查 source_to_test_mapping 静态映射
        2. 再用路径规律推断（<pkg>/tests/test_<mod>.py）
        """
        # 静态映射
        for pattern, modules in self.source_to_test_mapping.items():
            if pattern in source_file:
                return list(modules)

        # 路径规律推断
        return self._infer_by_convention(source_file, repo_root)

    def _infer_by_convention(self, source_file: str, repo_root: Path | None = None) -> list[str]:
        """基于目录约定推断测试文件。子类可覆盖。"""
        p = Path(source_file)
        stem = p.stem.lstrip("_")
        parent = str(p.parent)

        candidates = [
            f"{parent}/tests/test_{stem}.py",
            f"{parent}/test_{stem}.py",
            f"tests/test_{stem}.py",
        ]

        if repo_root:
            return [c for c in candidates if (repo_root / c).exists()]
        return candidates[:1]

    def source_path_to_test_label(self, test_file: str) -> str:
        """将测试文件路径转换为测试框架可识别的 label。

        pytest: 直接返回文件路径
        unittest (Django): tests/utils_tests/test_text.py → utils_tests.test_text
        """
        return test_file

    def build_test_cmd(self, targets: list[str]) -> str:
        """构建测试执行命令。"""
        if not targets:
            return ""
        return self.test_cmd_template.format(targets=" ".join(targets))

    def is_disallowed_label(self, label: str) -> bool:
        """检查测试 label 是否在黑名单中。"""
        if not label or not isinstance(label, str):
            return False
        s = label.strip()
        for p in self.disallowed_test_prefixes:
            if s == p or s.startswith(p + "."):
                return True
        return False

    def map_files_to_test_modules(self, files: list[str]) -> list[str]:
        """将源文件列表映射到测试模块列表。"""
        modules: list[str] = []
        for fp in files:
            inferred = self.infer_test_modules(fp)
            for m in inferred:
                if m not in modules:
                    modules.append(m)
        return modules

    def get_test_file_path(self, source_file: str) -> str:
        """确定合成测试文件应放置的路径。"""
        return "tests/test_synthetic.py"

    def generate_test_class(
        self,
        test_class_name: str,
        test_method_name: str,
        imports: list[str],
        test_body: str,
        target_node: str,
        expected_failure_reason: str,
        helper_code: str = "",
    ) -> str:
        """生成合成测试代码。默认生成 pytest 风格的函数。"""
        imports_str = "\n".join(sorted(set(imports)))

        # 缩进测试体
        indented_lines = []
        for line in test_body.split("\n"):
            if line.strip():
                stripped = line.lstrip()
                orig_indent = len(line) - len(stripped)
                indented_lines.append("    " + " " * orig_indent + stripped)
            else:
                indented_lines.append("")
        indented_body = "\n".join(indented_lines)

        if not indented_body.strip() or indented_body.strip() == "pass":
            func_name = target_node.split(":")[-1] if ":" in target_node else "target"
            indented_body = f"    # Synthetic test for {func_name}\n    assert True"

        helper_section = ""
        if helper_code and helper_code.strip():
            helper_section = f"\n\n# Helper classes and functions\n{helper_code}\n"

        return f'''"""
Synthetic test generated by TraceGen.
Target: {target_node}
Expected failure: {expected_failure_reason}
"""
{imports_str}{helper_section}


def {test_method_name}():
    """
    Test that verifies the synthetic bug.
    Expected: {expected_failure_reason or "Test should fail due to injected bug"}
    """
{indented_body}
'''

    def get_validation_profile(self, image_name: str) -> BaseProfile:
        """返回用于验证阶段的 BaseProfile 实例。"""
        from src.modules.validation.profiles.python import PythonProfile
        return PythonProfile(image_name=image_name)

    def infer_seed_test_cmd(self, seed_info: dict, max_total_labels: int = 6) -> str:
        """从 seed 元数据推断测试命令。默认返回空（由 adapter 走通用路径）。"""
        return ""

    def build_validation_test_cmd(
        self,
        fail_to_pass: list[str] | None,
        pass_to_pass: list[str] | None,
        test_selection_mode: str = "module_suite",
        max_fail_labels: int = 1,
        max_pass_labels: int = 1,
        max_total_labels: int = 6,
        modified_files: list[str] | None = None,
        target_node: str = "",
        planned_test_cmd: str = "",
        planned_test_modules: list[str] | None = None,
    ) -> str:
        """
        构建验证阶段的测试命令。

        Args:
            fail_to_pass: 预期失败的测试列表
            pass_to_pass: 预期通过的测试列表
            test_selection_mode: 测试选择模式 ("fast" | "module_suite")
            max_fail_labels: fast模式下最多选择的FAIL测试数
            max_pass_labels: fast模式下最多选择的PASS测试数
            max_total_labels: 总共最多选择的测试数
            modified_files: 修改的源文件列表
            target_node: 目标节点
            planned_test_cmd: Agent规划的测试命令
            planned_test_modules: Agent规划的测试模块

        Returns:
            测试命令字符串
        """
        # 优先策略：如果有 F2P/P2P 真实标签（来自实际测试执行），
        # 直接从中提取文件路径构建命令。这比 planned_test_cmd 更可靠，
        # 因为 planned_test_cmd 依赖静态映射（可能不完整/不正确）。
        if fail_to_pass or pass_to_pass:
            cmd = self._build_pytest_file_level_cmd(
                fail_to_pass=fail_to_pass,
                pass_to_pass=pass_to_pass,
                max_total_labels=max_total_labels,
            )
            if cmd:
                return cmd

        # Fallback 1: planned_test_cmd（框架兼容时使用）
        if planned_test_cmd and planned_test_cmd.strip():
            cmd = planned_test_cmd.strip()
            if self.test_framework == "pytest" and ("pytest" in cmd or "python -m pytest" in cmd):
                return cmd
            elif self.test_framework != "pytest" and "pytest" not in cmd:
                return cmd

        # Fallback 2: planned_test_modules
        if planned_test_modules and isinstance(planned_test_modules, list):
            modules = [m for m in planned_test_modules if m and isinstance(m, str)]
            if modules:
                cmd = self.build_test_cmd(modules[:max_total_labels])
                if cmd:
                    return cmd

        # Fallback 3: 文件级命令（F2P/P2P 为空时到达此处）
        return ""

    def _build_pytest_file_level_cmd(
        self,
        fail_to_pass: list[str] | None,
        pass_to_pass: list[str] | None,
        max_total_labels: int = 6,
    ) -> str:
        """
        构建pytest文件级测试命令（适用于pytest/sklearn/sympy）。

        策略：从FAIL_TO_PASS和PASS_TO_PASS中提取唯一的文件路径，运行整个文件。
        """
        files: list[str] = []

        # 提取FAIL_TO_PASS中的文件
        if fail_to_pass:
            for label in fail_to_pass:
                if not isinstance(label, str) or not label.strip():
                    continue
                # pytest格式: file.py::Class::method
                parts = label.split("::")
                if parts and parts[0] not in files:
                    files.append(parts[0])

        # 提取PASS_TO_PASS中的文件
        if pass_to_pass:
            for label in pass_to_pass:
                if not isinstance(label, str) or not label.strip():
                    continue
                parts = label.split("::")
                if parts and parts[0] not in files:
                    files.append(parts[0])

        # 限制文件数量
        files = files[:max_total_labels]

        if not files:
            return ""

        return f"pytest {' '.join(files)} -v --tb=short"

    def plan_test_suite(self, file_path: str, repo_root: Path) -> dict[str, Any]:
        """为合成 agent 规划测试套件。返回 planned dict。"""
        planned: dict[str, Any] = {
            "is_django": False,
            "test_modules": [],
            "test_files": [],
            "test_cmd": "",
        }

        test_modules = self.infer_test_modules(file_path, repo_root)
        if test_modules:
            # 过滤黑名单
            test_modules = [m for m in test_modules if not self.is_disallowed_label(m)]
            planned["test_modules"] = test_modules
            planned["test_cmd"] = self.build_test_cmd(test_modules)

            # 展开为具体文件
            test_files: list[str] = []
            for m in test_modules:
                if m.endswith(".py"):
                    test_files.append(m)
                else:
                    # 尝试展开目录
                    dir_path = repo_root / self.test_root / m
                    if dir_path.exists() and dir_path.is_dir():
                        for tf in sorted(dir_path.glob("*.py"))[:40]:
                            test_files.append(str(tf.relative_to(repo_root)))
                    else:
                        # 尝试作为文件
                        fp = repo_root / self.test_root / f"{m}.py"
                        if fp.exists():
                            test_files.append(str(fp.relative_to(repo_root)))
            planned["test_files"] = sorted(set(test_files))

        return planned

    # ── Django 兼容 ──

    @property
    def is_django(self) -> bool:
        return "django/django" in self.repo
